language: node_js
node_js:
- 4.4.4
script: gulp build
env:
  global:
    secure: xmKnSmSIukKJAHbzzK4+k4kOqy9c6wu+LNsfELsCv14uZ1nJZy2Fl6MTA0Rhkpf7XnrpAlXS3L943ORkgof/WYW5HyLLaPF5A5zbyF2wn5KdMXcQMDWjDQnLV+0UGXErBhD3l8YwfzvBnyxYZDjqG5Zz94SCOvtepdcCag7Nqi14e6z3RuxKoMJ0G4CVeEF/Bi1X/yqOLTcDrHFKpZ7unJ1xTjLneJfZuY78t0+z8mSiq1tc9NvllstMx2zergRXCuQQFqRr66CHAOUGwJL+JA1Xh0jWhDR0iTdBeQBRqZXPXEmHToOzJAxqk5BuIp7TUJBMFZXiZS8Xhs2zPL/rwhvuis02L3OnzWNQwX82DpNtqC6cSeMhbJ6mVLkC/tm5trToZ2xUrx4/yrbuD18s47uTVX+Q6NqRRyy/q2/7sIBy5TwB10TwFu9bmHBps7jAM5ptHVzgNDVDlXHB6btUvsSSe3oEpJP8Kjm2laCfYXD5/dP88SGJVdssKVsGtqjnklT2XDVeVoKGEh8/QKsaqFIdwFi+8rd9xY4clZKoaaZg/Ag8SrrIin68JjJRDbwmp4MfuRTnnLDUbvu4/+hqcuex5AQ6gBVD1m8F8VnPwlT+qLBCPfUxKcqlELNNrJtK15x5zoc41k04+EcqRHSyh/wUjUGOAceO5apeKNYuwCo=
